version: '3.8'

services:
  arbitrage-bot:
    build: .
    container_name: ba_ok_arbitrage
    restart: unless-stopped
    volumes:
      # 挂载日志目录到宿主机，便于查看日志
      - ./logs:/app/logs
    environment:
      - NODE_ENV=production
    # 如果需要网络访问，可以取消注释下面的端口映射
    # ports:
    #   - "3000:3000"
    # 设置时区
    environment:
      - TZ=Asia/Shanghai
    # 健康检查（可选）
    healthcheck:
      test: ["CMD", "node", "-e", "console.log('Health check')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s